### PR TITLE
Monorepo

### LINKED ISSUE #39: Combine Go Components into Single Mono-Repo
Bring all Mistify Go components into a single repo.

### PR DESCRIPTION
**Pull request by bbickerton**
Closes #39 

Merge coordinator, acomm, provider into the mistify monorepo preserving history. Update imports accordingly. Add common files.

Look at commits starting on Mar 01, 2016 (hash 4df71b2) for this PR. Older ones are "imported" history.

[Review on Reviewable](https://reviewable.io/reviews/mistifyio/mistify/45)

### CODE REVIEW

**Comment by mmlb** [comment]
Reviewed 62 of 62 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[.github/PULL_REQUEST_TEMPLATE, line 2 [r1]](https://reviewable.io:443/reviews/mistifyio/mistify/45#-KBoHbupfNuZDZB4pZNW:-KBoHbuq7nySor9HErMP:95540422) ([raw file](https://github.com/mistifyio/mistify/blob/ba597aa4ab92eaf7a6cc57706cc804c05860cd83/.github/PULL_REQUEST_TEMPLATE#L2)):_
Whats the intended use of Issue?

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify/45)_

**Comment by bbickerton** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[.github/PULL_REQUEST_TEMPLATE, line 2 [r1]](https://reviewable.io:443/reviews/mistifyio/mistify/45#-KBoHbupfNuZDZB4pZNW:-KBoHw5YyTsoqNUEvGX5:107721006) ([raw file](https://github.com/mistifyio/mistify/blob/ba597aa4ab92eaf7a6cc57706cc804c05860cd83/.github/PULL_REQUEST_TEMPLATE#L2)):_
`Issue:` is a heading for `Closes #XXX` I wasn't sure if just the later was clear enough that you should put an issue number in there.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify/45)_

**Comment by mmlb** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[.github/PULL_REQUEST_TEMPLATE, line 2 [r1]](https://reviewable.io:443/reviews/mistifyio/mistify/45#-KBoHbupfNuZDZB4pZNW:-KBoIKSDBM2Xy0izKu78:-1791346126) ([raw file](https://github.com/mistifyio/mistify/blob/ba597aa4ab92eaf7a6cc57706cc804c05860cd83/.github/PULL_REQUEST_TEMPLATE#L2)):_
oh, hmm  maybe something like

```
# issues affected by this pr, see https://help.github.com/articles/closing-issues-via-commit-messages
```

?

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify/45)_

**Comment by joshie** [comment]
LGTM (or maybe just okay... :D)

**Comment by bbickerton** [comment]
Review status: 56 of 57 files reviewed at latest revision, 1 unresolved discussion.

---

_[.github/PULL_REQUEST_TEMPLATE, line 2 [r1]](https://reviewable.io:443/reviews/mistifyio/mistify/45#-KBoHbupfNuZDZB4pZNW:-KBoQOYf7VlL_JAK1Rfz:-1149518530) ([raw file](https://github.com/mistifyio/mistify/blob/ba597aa4ab92eaf7a6cc57706cc804c05860cd83/.github/PULL_REQUEST_TEMPLATE#L2)):_
Tweaked wording

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify/45)_

**Comment by mmlb** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify/45)_

**Pull request merged**
