### PR TITLE
Systemd Provider

### LINKED ISSUE #52: Create systemd Provider
Provide the following funcitonality:
- Create process : accept parameters and generate file via template
- Remove process
- Start/Stop/Restart process
- Status of process
- List managed processes

### PR DESCRIPTION
**Pull request by bbickerton**
List any issues affected/resolved by this pr. https://github.com/blog/1506-closing-issues-via-pull-requests :
Resolves #52 

Description:
Adds a basic Systemd Provider with the following task handlers available:
- systemd-create
- systemd-disable
- systemd-enable
- systemd-get
- systemd-list
- systemd-remove
- systemd-restart
- systemd-start
- systemd-stop

---

This change is [Reviewable](https://reviewable.io/reviews/mistifyio/mistify/66)

### CODE REVIEW

**Comment by mmlb** [comment]
I'm thinking we should test this withing a mistify-os container like I'm doing in lochness.

---

Review status: 0 of 25 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify/66#-:-KDiy-96_0nkyi6SULjc:1299887638)_

**Comment by bbickerton** [comment]
Since Travis only has ubuntu trusty, need to set it up like lochness to run in a mistifyos docker container.

**Comment by joshie** [comment]
LGTM

**Comment by mmlb** [comment]
Reviewed 16 of 28 files at r1, 13 of 13 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_[providers/systemd/action.go, line 43 [r3]](https://reviewable.io:443/reviews/mistifyio/mistify/66#-KE7t-ArzzuWUscRwnbh:-KE7t-AsppeThRQtLKLT:134584401) ([raw file](https://github.com/mistifyio/mistify/blob/7ab53bc5b8be932c55882f31dba1e77f30307192/providers/systemd/action.go#L43)):_
shouldn't this be a struct member?

---

_[providers/systemd/config.go, line 36 [r3]](https://reviewable.io:443/reviews/mistifyio/mistify/66#-KE7uSBLY8g0Z8JU_yTJ:-KE7uSBLY8g0Z8JU_yTK:819597023) ([raw file](https://github.com/mistifyio/mistify/blob/7ab53bc5b8be932c55882f31dba1e77f30307192/providers/systemd/config.go#L36)):_
this seems weird to trim any spaces here

---

_[providers/systemd/config_test.go, line 27 [r3]](https://reviewable.io:443/reviews/mistifyio/mistify/66#-KE7utmlHv-0gRzTnRl0:-KE7utmlHv-0gRzTnRl1:-939487973) ([raw file](https://github.com/mistifyio/mistify/blob/7ab53bc5b8be932c55882f31dba1e77f30307192/providers/systemd/config_test.go#L27)):_
yeah I would expect for this to be an error

---

_[providers/systemd/create.go, line 43 [r3]](https://reviewable.io:443/reviews/mistifyio/mistify/66#-KE7vBe3m8-Qev8tffqo:-KE7vBe3m8-Qev8tffqp:1420513309) ([raw file](https://github.com/mistifyio/mistify/blob/7ab53bc5b8be932c55882f31dba1e77f30307192/providers/systemd/create.go#L43)):_
is there an issue for this?

---

_[providers/systemd/create_test.go, line 28 [r3]](https://reviewable.io:443/reviews/mistifyio/mistify/66#-KE7w9WNMcw-zVbGmpzZ:-KE7w9WNMcw-zVbGmpz_:544107222) ([raw file](https://github.com/mistifyio/mistify/blob/7ab53bc5b8be932c55882f31dba1e77f30307192/providers/systemd/create_test.go#L28)):_
zfs-create...? isn't it supposed to be systemd-create?

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify/66)_

**Comment by bbickerton** [comment]
Review status: 25 of 26 files reviewed at latest revision, 5 unresolved discussions.

---

_[providers/systemd/action.go, line 43 [r3]](https://reviewable.io:443/reviews/mistifyio/mistify/66#-KE7t-ArzzuWUscRwnbh:-KE80skY9KNlfOABH0il:1086663035) ([raw file](https://github.com/mistifyio/mistify/blob/7ab53bc5b8be932c55882f31dba1e77f30307192/providers/systemd/action.go#L43)):_
Is it ok to leave that open? I got more of a "open and close as needed" feel from https://godoc.org/github.com/coreos/go-systemd/dbus#New . It's entirely possible I read too much into that and it's fine to hold it open, in which case I'll create it in `systemd.New()` and put it in the struct.

---

_[providers/systemd/config.go, line 36 [r3]](https://reviewable.io:443/reviews/mistifyio/mistify/66#-KE7uSBLY8g0Z8JU_yTJ:-KE8-lIuU9wGB9jH3KCg:1537092575) ([raw file](https://github.com/mistifyio/mistify/blob/7ab53bc5b8be932c55882f31dba1e77f30307192/providers/systemd/config.go#L36)):_
It trims leading and trailing spaces.

---

_[providers/systemd/config_test.go, line 27 [r3]](https://reviewable.io:443/reviews/mistifyio/mistify/66#-KE7utmlHv-0gRzTnRl0:-KE8-vXm_y8fATlFTXbI:537973474) ([raw file](https://github.com/mistifyio/mistify/blob/7ab53bc5b8be932c55882f31dba1e77f30307192/providers/systemd/config_test.go#L27)):_
Depends if you agree with leading/trailing whitespace trimming. Very common in the webdev world, maybe not so common systems level?

---

_[providers/systemd/create.go, line 43 [r3]](https://reviewable.io:443/reviews/mistifyio/mistify/66#-KE7vBe3m8-Qev8tffqo:-KE809Z37J42O2zgdCzU:-211781778) ([raw file](https://github.com/mistifyio/mistify/blob/7ab53bc5b8be932c55882f31dba1e77f30307192/providers/systemd/create.go#L43)):_
I'll create one in the new repo  after the migration.

---

_[providers/systemd/create_test.go, line 28 [r3]](https://reviewable.io:443/reviews/mistifyio/mistify/66#-KE7w9WNMcw-zVbGmpzZ:-KE80POedYMrjER6u2KC:74430482) ([raw file](https://github.com/mistifyio/mistify/blob/7ab53bc5b8be932c55882f31dba1e77f30307192/providers/systemd/create_test.go#L28)):_
Ah, woops. Doesn't really matter here, but good to fix.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify/66)_

**Comment by mmlb** [comment]
Review status: 25 of 26 files reviewed at latest revision, 5 unresolved discussions.

---

_[providers/systemd/action.go, line 43 [r3]](https://reviewable.io:443/reviews/mistifyio/mistify/66#-KE7t-ArzzuWUscRwnbh:-KE83I0PcZc-B6YAFIO5:1503558264) ([raw file](https://github.com/mistifyio/mistify/blob/7ab53bc5b8be932c55882f31dba1e77f30307192/providers/systemd/action.go#L43)):_
Yeah I think so, its similar to a tcp/udp Conn, open up early in the program and keep it around. each dbus connection is going to lead to a new unix:// connection + auth each request currently.

---

_[providers/systemd/config.go, line 36 [r3]](https://reviewable.io:443/reviews/mistifyio/mistify/66#-KE7uSBLY8g0Z8JU_yTJ:-KE82Pi-o1QLTdorw1A6:-126092486) ([raw file](https://github.com/mistifyio/mistify/blob/7ab53bc5b8be932c55882f31dba1e77f30307192/providers/systemd/config.go#L36)):_
my point is this shouldn't be done here.

---

_[providers/systemd/config_test.go, line 27 [r3]](https://reviewable.io:443/reviews/mistifyio/mistify/66#-KE7utmlHv-0gRzTnRl0:-KE82TlmhQnSPcOkYTNm:-1185600271) ([raw file](https://github.com/mistifyio/mistify/blob/7ab53bc5b8be932c55882f31dba1e77f30307192/providers/systemd/config_test.go#L27)):_
nope, we aren't forgiving. We expect for callers to mean what they say and say what they mean.

---

_[providers/systemd/create.go, line 43 [r3]](https://reviewable.io:443/reviews/mistifyio/mistify/66#-KE7vBe3m8-Qev8tffqo:-KE82dczjIG0YF129RwR:678027858) ([raw file](https://github.com/mistifyio/mistify/blob/7ab53bc5b8be932c55882f31dba1e77f30307192/providers/systemd/create.go#L43)):_
sgtm

---

_[providers/systemd/create_test.go, line 28 [r3]](https://reviewable.io:443/reviews/mistifyio/mistify/66#-KE7w9WNMcw-zVbGmpzZ:-KE82fh-_uKKFSxhlKqo:-413892381) ([raw file](https://github.com/mistifyio/mistify/blob/7ab53bc5b8be932c55882f31dba1e77f30307192/providers/systemd/create_test.go#L28)):_
you probably want to do

```
cd providers/systemd
sed -i 's|\(acomm.NewRequest("\)zfs|\1systemd|'
```

a lot of other cases too ;)

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify/66)_

**Comment by mmlb** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify/66)_

**Comment by bbickerton** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

_[providers/systemd/action.go, line 43 [r3]](https://reviewable.io:443/reviews/mistifyio/mistify/66#-KE7t-ArzzuWUscRwnbh:-KE8FFcHZFj5m6GI4rwT:-499146009) ([raw file](https://github.com/mistifyio/mistify/blob/7ab53bc5b8be932c55882f31dba1e77f30307192/providers/systemd/action.go#L43)):_
Done.

---

_[providers/systemd/config.go, line 36 [r3]](https://reviewable.io:443/reviews/mistifyio/mistify/66#-KE7uSBLY8g0Z8JU_yTJ:-KE8BtHf6thfHc4KocF5:217833762) ([raw file](https://github.com/mistifyio/mistify/blob/7ab53bc5b8be932c55882f31dba1e77f30307192/providers/systemd/config.go#L36)):_
Unforgiving it is. Done.

---

_[providers/systemd/create_test.go, line 28 [r3]](https://reviewable.io:443/reviews/mistifyio/mistify/66#-KE7w9WNMcw-zVbGmpzZ:-KE84bTNFOq7PhyL8cor:1758359711) ([raw file](https://github.com/mistifyio/mistify/blob/7ab53bc5b8be932c55882f31dba1e77f30307192/providers/systemd/create_test.go#L28)):_
Fixed.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify/66)_

**Comment by mmlb** [comment]
Reviewed 15 of 15 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify/66)_

**Pull request merged**
